[project]
name = "almono"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asciinema>=2.4.0",
    "lxml>=6.0.2",
    "websockets>=15.0.1",
]
